---
- hosts: all
  become: yes
  tasks:
  - name: i want to install ansible node
    apt:
     name: apache2
     state: present

  - name: i want to start web server
    service:
    name: apache2
    state: started
    

