---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git now
    apt:
      name: git
      state: present

  - name: i want to install ubuntu machine
    apt:
      name: ubuntu
      state: present