---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git now
    apt:
      name: git
      state: present
  when: ansible_os_family=="Debian"
  - name: i want to install RedHat machine
    yum:
      name: RedHat
      state: present
  when: ansible_os_family=="Debian"
