---
- hosts: 172.31.30.172
  become: yes
  tasks:
  - name: git
    apt: 
      name: git
      state: present

  - name: tree
    apt:
      name: tree
      apt: present

  - name: wget
    apt: 
      name: wget
      state: present    
