---
- hosts: all
  become: yes
  tasks:
   - name: i want to install a web server 
     apt:
       name: apache2
       state: present
     when: ansible_os_family=="Debian"

    - name: i want to install a web server 
      apt:
        name: RedHat
        state: present
        
     when: ansible_os_family=="Debian"
